name       : yelp-xsl
version    : 3.34.0
release    : 8
source     :
    - https://download.gnome.org/sources/yelp-xsl/3.34/yelp-xsl-3.34.0.tar.xz : e8063aee67d1df634f3d062f1c28130b2dabb3c0c66396b1af90388f34e14ee2
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MIT
component  : desktop.gnome.doc
summary    : Yelp XSL Stylesheets
description: |
    The Yelp XSL package contains XSL stylesheets that are used by the Yelp help browser to format Docbook and Mallard documents.
builddeps  :
    - itstool
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
