name       : yelp-xsl
version    : '40.0'
release    : 14
source     :
    - https://download.gnome.org/sources/yelp-xsl/40/yelp-xsl-40.0.tar.xz : 361ecd4d33fccdb3bb08a687f60e5c3e909d2e9e3b022d844e049820d0cf62b0
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MIT
component  : desktop.gnome.doc
summary    : Yelp XSL Stylesheets
description: |
    The Yelp XSL package contains XSL stylesheets that are used by the Yelp help browser to format Docbook and Mallard documents.
builddeps  :
    - itstool
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
