name       : yelp-xsl
version    : 3.20.1
release    : 5
source     :
    - http://ftp.gnome.org/pub/gnome/sources/yelp-xsl/3.20/yelp-xsl-3.20.1.tar.xz : dc61849e5dca473573d32e28c6c4e3cf9c1b6afe241f8c26e29539c415f97ba0
license    :
    - GPL-2.0
    - LGPL-2.1
    - MIT
summary    : Yelp XSL Stylesheets
builddeps  :
    - itstool
patterns   :
    - devel: /usr/share/pkgconfig
description: |
    The Yelp XSL package contains XSL stylesheets that are used by the Yelp help browser to format Docbook and Mallard documents.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
