name       : yelp-xsl
version    : 3.38.1
release    : 11
source     :
    - https://download.gnome.org/sources/yelp-xsl/3.38/yelp-xsl-3.38.1.tar.xz : b321563da6ab7fa8b989adaf1a91262059696316b4ddca2288fddcfed8dcdf67
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MIT
component  : desktop.gnome.doc
summary    : Yelp XSL Stylesheets
description: |
    The Yelp XSL package contains XSL stylesheets that are used by the Yelp help browser to format Docbook and Mallard documents.
builddeps  :
    - itstool
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
