name        : yelp-xsl
version     : 3.18.1
release     : 4
source     :
    - http://ftp.gnome.org/pub/gnome/sources/yelp-xsl/3.18/yelp-xsl-3.18.1.tar.xz : 00870fbe59a1bc7797b385fce16386917e2987c404e9b5a7adcf0036f1c1ba62
license     :
    - GPL-2.0
    - LGPL-2.1
    - MIT
summary     : Yelp XSL Stylesheets
builddeps   :
    - itstool
description : |
    The Yelp XSL package contains XSL stylesheets that are used by the Yelp help browser to format Docbook and Mallard documents.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
